### ISSUE TITLE
Adding title names for each page

### ISSUE THREAD

**Issue by unfaiyted** [QualityCapstone/QSHE#69]
Current each page has the same name as the other pages, go into the partial on each of our templates and update the page to have a name for that specific page

Example: 

<head th:replace="partials/layout :: header (page='Profile')">

will produce Q-She - Profile in the bar

**Comment by unfaiyted** [comment]
code: ex
> `<head th:replace="partials/layout :: header (page='Profile')">`

**Comment by Monicacholico** [comment]
Added title names to every template
